version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - mynetwork

  ntp:
    image: cturra/ntp
    restart: always
    networks:
      - mynetwork

volumes:
  jenkins_home:

networks:
  mynetwork:
    driver: bridge
